#port setup
server.port=8080
# config H2 Database on RAM
spring.datasource.url=jdbc:h2:mem:sqlquestdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# on console H2 in browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console